apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mahasiva-amazon/eks-drdemo-apps.git
    targetRevision: HEAD
    path: app_1
    helm:
      valueFiles:
      - apps/helm_values/app_1_values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: drapps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
